apiVersion: v1
kind: Service
metadata:
  name: graphql-dart-angel3
  labels:
    app: graphql-dart-angel3
    benchmark: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: graphql-dart-angel3
