apiVersion: v1
kind: Service
metadata:
  name: deno-graphql-hono
  labels:
    app: deno-graphql-hono
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deno-graphql-hono
---
apiVersion: v1
kind: Service
metadata:
  name: deno-graphql-hono-headless
  labels:
    app: deno-graphql-hono
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deno-graphql-hono
