apiVersion: v1
kind: ConfigMap
metadata:
  name: benchmark-config
  labels:
    app: benchmark-deno-grpc-js
data:
  PORT: "50051"
  DB_HOST: "postgresql.benchmark.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "benchmark"
  DB_USER: "benchmark"
  REDIS_HOST: "redis.benchmark.svc.cluster.local"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  APP_VERSION: "1.0.0"
