apiVersion: v1
kind: Service
metadata:
  name: kotlin-graphql-kotlin
  labels:
    app: kotlin-graphql-kotlin
    benchmark: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: kotlin-graphql-kotlin
