apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-graphql-go-config
  labels:
    app: graphql-graphql-go
data:
  PORT: "8080"
  DATABASE_URL: "postgres://benchmark:benchmark@postgres:5432/benchmark"
  REDIS_URL: "redis://redis:6379"
