apiVersion: v1
kind: ConfigMap
metadata:
  name: graalvm-grpc-quarkus-config
  labels:
    app: graalvm-grpc-quarkus
    benchmark: "true"
data:
  QUARKUS_GRPC_SERVER_PORT: "50051"
  QUARKUS_DATASOURCE_REACTIVE_URL: "postgresql://benchmark-postgres:5432/benchmark"
  QUARKUS_REDIS_HOSTS: "redis://benchmark-redis:6379"
  QUARKUS_LOG_LEVEL: "INFO"
