apiVersion: v1
kind: Service
metadata:
  name: graalvm-grpc-quarkus
  labels:
    app: graalvm-grpc-quarkus
    benchmark: "true"
spec:
  type: ClusterIP
  selector:
    app: graalvm-grpc-quarkus
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
