apiVersion: v1
kind: Pod
metadata:
  name: pgtest2
  namespace: benchmark
spec:
  hostNetwork: true
  restartPolicy: Never
  activeDeadlineSeconds: 15
  containers:
  - name: pg
    image: postgres:16-alpine
    command:
    - psql
    - -h
    - 192.168.1.52
    - -U
    - db_admin
    - -d
    - postgres
    - -c
    - SELECT datname FROM pg_database WHERE datistemplate = false;
    env:
    - name: PGPASSWORD
      value: Admin@123
