apiVersion: v1
kind: ConfigMap
metadata:
  name: csharp-protobuf-net-grpc-config
  labels:
    app: csharp-protobuf-net-grpc
    benchmark: "true"
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_EnableDiagnostics: "0"
