apiVersion: v1
kind: Service
metadata:
  name: csharp-protobuf-net-grpc
  labels:
    app: csharp-protobuf-net-grpc
    benchmark: "true"
spec:
  type: ClusterIP
  selector:
    app: csharp-protobuf-net-grpc
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
