apiVersion: v1
kind: Service
metadata:
  name: graphql-rust-actix
  labels:
    app: graphql-rust-actix
spec:
  selector:
    app: graphql-rust-actix
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  type: ClusterIP
