apiVersion: v1
kind: Service
metadata:
  name: graalvm-gmicronaut
  labels:
    app: graalvm-gmicronaut
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: graalvm-gmicronaut
---
apiVersion: v1
kind: Service
metadata:
  name: graalvm-gmicronaut-headless
  labels:
    app: graalvm-gmicronaut
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: graalvm-gmicronaut
