apiVersion: v1
kind: Service
metadata:
  name: graphql-entitygraphql
spec:
  selector:
    app: graphql-entitygraphql
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: ClusterIP
