apiVersion: v1
kind: Service
metadata:
  name: deno-deno-serve
  labels:
    app: deno-deno-serve
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deno-deno-serve
---
apiVersion: v1
kind: Service
metadata:
  name: deno-deno-serve-headless
  labels:
    app: deno-deno-serve
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: deno-deno-serve
