apiVersion: v1
kind: Service
metadata:
  name: nodejs-nestjs
  labels:
    app: nodejs-nestjs
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodejs-nestjs
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-nestjs-headless
  labels:
    app: nodejs-nestjs
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: nodejs-nestjs
