apiVersion: v1
kind: Service
metadata:
  name: graalvm-grpc-java
  labels:
    app: graalvm-grpc-java
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: grpc
  selector:
    app: graalvm-grpc-java
---
apiVersion: v1
kind: Service
metadata:
  name: graalvm-grpc-java-headless
  labels:
    app: graalvm-grpc-java
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grpc
  selector:
    app: graalvm-grpc-java
