apiVersion: v1
kind: Service
metadata:
  name: graalvm-vertx
  labels:
    app: graalvm-vertx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: graalvm-vertx
---
apiVersion: v1
kind: Service
metadata:
  name: graalvm-vertx-headless
  labels:
    app: graalvm-vertx
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: graalvm-vertx
