apiVersion: v1
kind: ConfigMap
metadata:
  name: csharp-grpc-dotnet-config
  labels:
    app: csharp-grpc-dotnet
    benchmark: "true"
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_EnableDiagnostics: "0"
