apiVersion: v1
kind: Service
metadata:
  name: csharp-grpc-dotnet
  labels:
    app: csharp-grpc-dotnet
    benchmark: "true"
spec:
  type: ClusterIP
  selector:
    app: csharp-grpc-dotnet
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
