apiVersion: v1
kind: ConfigMap
metadata:
  name: python-grpc-betterproto-config
  labels:
    app: python-grpc-betterproto
    component: benchmark
data:
  GRPC_PORT: "50051"
  GRPC_MAX_WORKERS: "10"
