apiVersion: v1
kind: Service
metadata:
  name: python-grpc-betterproto
  labels:
    app: python-grpc-betterproto
    component: benchmark
spec:
  type: ClusterIP
  selector:
    app: python-grpc-betterproto
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
