apiVersion: v1
kind: Service
metadata:
  name: benchmark-grpc-kotlin
  labels:
    app: benchmark-grpc-kotlin
    component: grpc-server
    benchmark: "true"
spec:
  type: ClusterIP
  selector:
    app: benchmark-grpc-kotlin
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
