apiVersion: v1
kind: Service
metadata:
  name: kotlin-spring
  labels:
    app: kotlin-spring
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: kotlin-spring
---
apiVersion: v1
kind: Service
metadata:
  name: kotlin-spring-headless
  labels:
    app: kotlin-spring
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: kotlin-spring
