apiVersion: v1
kind: Service
metadata:
  name: nodejs-fastify
  namespace: benchmark
  labels:
    app: nodejs-fastify
    tier: api
spec:
  type: ClusterIP
  selector:
    app: nodejs-fastify
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
