apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-python-ariadne-config
  labels:
    app: graphql-python-ariadne
    benchmark: "true"
data:
  PORT: "8080"
  DATABASE_URL: "postgres://benchmark:benchmark@postgresql.benchmark.svc.cluster.local:5432/benchmark"
  REDIS_URL: "redis://redis.benchmark.svc.cluster.local:6379"
