apiVersion: v1
kind: Service
metadata:
  name: dart-grpc-grpc-dart
  labels:
    app: dart-grpc-grpc-dart
    component: benchmark
spec:
  type: ClusterIP
  selector:
    app: dart-grpc-grpc-dart
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
