apiVersion: v1
kind: Service
metadata:
  name: benchmark-kitex
  labels:
    app: benchmark-kitex
spec:
  type: ClusterIP
  selector:
    app: benchmark-kitex
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: kitex
