apiVersion: v1
kind: Service
metadata:
  name: kotlin-ktor
  namespace: benchmark
  labels:
    app: kotlin-ktor
    tier: api
spec:
  type: ClusterIP
  selector:
    app: kotlin-ktor
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  sessionAffinity: None
