# Overlay for graalvm-rest-helidon
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: benchmark

resources:
  - ../../../../base

commonLabels:
  app: graalvm-rest-helidon
  benchmark-protocol: rest
  benchmark-environment: graalvm
  benchmark-framework: helidon

namePrefix: ""

patches:
  - target:
      kind: Deployment
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: graalvm-rest-helidon
      - op: replace
        path: /spec/selector/matchLabels/app
        value: graalvm-rest-helidon
      - op: replace
        path: /spec/template/metadata/labels/app
        value: graalvm-rest-helidon
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: benchmark/graalvm-rest-helidon:latest
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: graalvm-rest-helidon-config

  - target:
      kind: Service
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: graalvm-rest-helidon
      - op: replace
        path: /spec/selector/app
        value: graalvm-rest-helidon

  - target:
      kind: ConfigMap
      name: PLACEHOLDER-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: graalvm-rest-helidon-config
      - op: replace
        path: /data/PORT
        value: "8080"
