apiVersion: v1
kind: Service
metadata:
  name: rust-warp
  labels:
    app: rust-warp
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: rust-warp
---
apiVersion: v1
kind: Service
metadata:
  name: rust-warp-headless
  labels:
    app: rust-warp
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: rust-warp
