apiVersion: v1
kind: Service
metadata:
  name: python-fastapi
  labels:
    app: python-fastapi
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: python-fastapi
---
apiVersion: v1
kind: Service
metadata:
  name: python-fastapi-headless
  labels:
    app: python-fastapi
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: python-fastapi
