apiVersion: v1
kind: Service
metadata:
  name: kotlin-dgs-graphql
  labels:
    app: kotlin-dgs-graphql
    benchmark: "true"
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: kotlin-dgs-graphql
