# Overlay for csharp-graphql-graphql-dotnet
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: benchmark

resources:
  - ../../../base

commonLabels:
  app: csharp-graphql-graphql-dotnet
  benchmark-protocol: graphql
  benchmark-environment: csharp
  benchmark-framework: graphql-dotnet

namePrefix: ""

patches:
  - target:
      kind: Deployment
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: csharp-graphql-graphql-dotnet
      - op: replace
        path: /spec/selector/matchLabels/app
        value: csharp-graphql-graphql-dotnet
      - op: replace
        path: /spec/template/metadata/labels/app
        value: csharp-graphql-graphql-dotnet
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: benchmark/csharp-graphql-graphql-dotnet:latest
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: csharp-graphql-graphql-dotnet-config

  - target:
      kind: Service
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: csharp-graphql-graphql-dotnet
      - op: replace
        path: /spec/selector/app
        value: csharp-graphql-graphql-dotnet

  - target:
      kind: ConfigMap
      name: PLACEHOLDER-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: csharp-graphql-graphql-dotnet-config
      - op: replace
        path: /data/PORT
        value: "8080"
