apiVersion: v1
kind: Service
metadata:
  name: graalvm-micronaut-grpc
  labels:
    app: graalvm-micronaut-grpc
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: grpc
  selector:
    app: graalvm-micronaut-grpc
---
apiVersion: v1
kind: Service
metadata:
  name: graalvm-micronaut-grpc-headless
  labels:
    app: graalvm-micronaut-grpc
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: grpc
  selector:
    app: graalvm-micronaut-grpc
