apiVersion: v1
kind: ConfigMap
metadata:
  name: csharp-magiconion-config
  labels:
    app: csharp-magiconion
    benchmark: "true"
data:
  ASPNETCORE_ENVIRONMENT: "Production"
  DOTNET_EnableDiagnostics: "0"
