apiVersion: v1
kind: Service
metadata:
  name: rust-axum
  labels:
    app: rust-axum
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: rust-axum
---
apiVersion: v1
kind: Service
metadata:
  name: rust-axum-headless
  labels:
    app: rust-axum
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: rust-axum
