apiVersion: v1
kind: ConfigMap
metadata:
  name: csharp-minimalapi-config
  namespace: benchmark
  labels:
    app: csharp-minimalapi
data:
  database.url: "Host=spsql.home.arpa;Port=5432;Database=benchmark_api;Username=app;Password=${DB_PASSWORD};Maximum Pool Size=25;Connection Timeout=30;"
  redis.url: "redis.home.arpa:30379,Password=${DB_PASSWORD},defaultDatabase=0,ssl=false"
---
apiVersion: v1
kind: Secret
metadata:
  name: csharp-minimalapi-secrets
  namespace: benchmark
  labels:
    app: csharp-minimalapi
type: Opaque
stringData:
  database-password: ${DB_PASSWORD}
  redis-password: ${DB_PASSWORD}
