apiVersion: v1
kind: Service
metadata:
  name: csharp-minimalapi
  namespace: benchmark
  labels:
    app: csharp-minimalapi
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: health
  selector:
    app: csharp-minimalapi
---
apiVersion: v1
kind: Service
metadata:
  name: csharp-minimalapi-headless
  namespace: benchmark
  labels:
    app: csharp-minimalapi
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: csharp-minimalapi
