apiVersion: v1
kind: Service
metadata:
  name: benchmark-connectrpc
  labels:
    app: benchmark-connectrpc
spec:
  type: ClusterIP
  selector:
    app: benchmark-connectrpc
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: connectrpc
