# Overlay for rust-rest-rocket
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: benchmark

resources:
  - ../../../../base

commonLabels:
  app: rust-rest-rocket
  benchmark-protocol: rest
  benchmark-environment: rust
  benchmark-framework: rocket

namePrefix: ""

patches:
  - target:
      kind: Deployment
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: rust-rest-rocket
      - op: replace
        path: /spec/selector/matchLabels/app
        value: rust-rest-rocket
      - op: replace
        path: /spec/template/metadata/labels/app
        value: rust-rest-rocket
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: benchmark/rust-rest-rocket:latest
      - op: replace
        path: /spec/template/spec/containers/0/ports/0/containerPort
        value: 8080
      - op: replace
        path: /spec/template/spec/containers/0/envFrom/0/configMapRef/name
        value: rust-rest-rocket-config

  - target:
      kind: Service
      name: PLACEHOLDER
    patch: |-
      - op: replace
        path: /metadata/name
        value: rust-rest-rocket
      - op: replace
        path: /spec/selector/app
        value: rust-rest-rocket

  - target:
      kind: ConfigMap
      name: PLACEHOLDER-config
    patch: |-
      - op: replace
        path: /metadata/name
        value: rust-rest-rocket-config
      - op: replace
        path: /data/PORT
        value: "8080"
