# Server
server.port=${PORT:8080}

# GraphQL
spring.graphql.path=/graphql
spring.graphql.graphiql.enabled=false
spring.graphql.introspection.disabled=true

# PostgreSQL
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver

# Redis
spring.data.redis.url=${REDIS_URL}

# Logging
logging.level.root=WARN
logging.level.benchmark=INFO
