apiVersion: v1
kind: Service
metadata:
  name: java-micronaut
  labels:
    app: java-micronaut
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: java-micronaut
---
apiVersion: v1
kind: Service
metadata:
  name: java-micronaut-headless
  labels:
    app: java-micronaut
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: java-micronaut
