apiVersion: v1
kind: Service
metadata:
  name: benchmark-grpc-go
  labels:
    app: benchmark-grpc-go
spec:
  type: ClusterIP
  selector:
    app: benchmark-grpc-go
  ports:
    - port: 50051
      targetPort: 50051
      protocol: TCP
      name: grpc
